name: citizenjoe
favicon: null
layout_spectrum: 0.35101
typography_spectrum: 0.51299
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f4f4f4'
    - '#68625f'
    - '#b0afaa'
    - '#242220'
    - '#000000'
  brandStrength: 0.5
  lightness: 0.4375
  saturation: 0.4375
  rhythmicContrast: 0.5
purpose: []
