name: citizenjoe
favicon: null
layout_spectrum: 0.74119
typography_spectrum: 1
title: citizenjoe
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#090909'
    - '#ffffff'
    - '#39598c'
    - '#572912'
    - '#866425'
  brandStrength: 0.6875
  lightness: 0.4375
  saturation: 0.4375
  rhythmicContrast: 0.5
purpose: []
